<?php
/**
 * Name: Jay Dawson II
 * Date:2/23/2023
 * File:medical_student.class.php
 * Description:
 */

class MedicalStudent extends GradStudent{
    private $mcat;
    private static $student_count;

    public function __construct($name, $gender, $major, $gpa, $program,$mcat)
    {
        parent::__construct($name, $gender, $major, $gpa, $program);
        $this->mcat =$mcat;
        return $this;


    }

    /**
     * @return mixed
     */
    public function getMcat()
    {
        return $this->mcat;
    }

    /**
     * @param mixed $mcat
     * @return MedicalStudent
     */
    public function setMcat($mcat)
    {
        $this->mcat = $mcat;
        return $this;
    }

    /**
     * @return mixed
     */
    public static function getStudentCount()
    {
        return self::$student_count;
    }

    /**
     * @param mixed $student_count
     */
    public static function setStudentCount($student_count): void
    {
        self::$student_count = $student_count;
    }

    public function toString()
    {
        parent::toString(); // TODO: Change the autogenerated stub
        echo "<br>MCAT: ",$this->getMcat();
    }
}